### PR TITLE
[WIP] refactored css definitions for kikar into a less file.

### PR DESCRIPTION
**Pull request by yotammanor**
@OriHoch Does that make better sense this way?

### CODE REVIEW

**Comment by OriHoch** [comment]
yes, and also you need to add an import to the kikar less here:
https://github.com/hasadna/Open-Knesset/blob/master/less/app.less

**Comment by OriHoch** [comment]
@yotammanor ?

**Comment by yotammanor** [comment]
Sorry, missed the mention.
Doing it right away.

**Comment by yotammanor** [comment]
Done.
@OriHoch now it's ready.

**Pull request merged**
