### PR TITLE
#546 - recreating vote should not change the vote id

### PR DESCRIPTION
**Pull request by OriHoch**

### CODE REVIEW

**Comment by OriHoch** [comment]
there are some changes in #547 that conflict with these changes, I'll open a new pull reuqest for both of them together

**Comment by alonisser** [comment]
@OriHoch is there a trest for this change? since this is a very important part of oKnesset functionality I guess there should be (can be in another commit later of course - not blocking the merge for now, not going to nitpick .. )

**Comment by OriHoch** [comment]
no test..

**Comment by alonisser** [comment]
I'll add a todo. some day some time..

**Pull request closed without merging**
