### PR TITLE
fix #543 - added kikar statuses to committee's detail view

### LINKED ISSUE #543: Add feed of Facebook Statuses (from Kikar) to Committee's detail page
Search all statuses where given tag is mentioned as text, or is tagged with the same tag.

### PR DESCRIPTION
**Pull request by yotammanor**
#### Relating issues 
-  fixes #543

### CODE REVIEW

**Comment by yotammanor** [comment]
@OriHoch added another pr. It includes pull request #587 , but it is separated for convenience.

**Comment by yotammanor** [comment]
@OriHoch 
Translation strings should be:
(where the commmittee's name is mentioned)  --> (היכן שמוזכר שם הוועדה)

**Comment by alonisser** [comment]
@yotammanor please look at #610

**Comment by yotammanor** [comment]
@OriHoch the translation strings were not updated. Can you take care of that please? :)

**Comment by alonisser** [comment]
@yotammanor can you point the lines in django.po that are not updated so I can check ?

**Comment by OriHoch** [comment]
@yotammanor - fixed in v3.8.2 and deployed

**Pull request merged**
