### PR TITLE
Added Facebook statuses from kikar to member page

### LINKED ISSUE #541: Add feed of Facebook Statuses (from Kikar) to MK page

### PR DESCRIPTION
**Pull request by yotammanor**
#### Relating issues 
- Fixes #541 

#### Change list
- added Facebook statuses from kikar to member page.

### CODE REVIEW

**Comment by yotammanor** [comment]
@OriHoch  - I also added translation strings, but it was done windows-style. I'm not sure if it affects anything, but be advised. 

Also, there's whole bunch of styling done. It would be nice if someone could review it.

**Comment by OriHoch** [comment]
@yotammanor 
about the translations, would be best if you reverted those changes and just wrote in the PR what are the required translations and I will do them

about the styling - please attach a screenshot

**Comment by yotammanor** [comment]
Added a commit to revert translations to hasadna/master of current date-time.

Translation strings to be added be: 

msgid "Apologies, your browser does not support displaying videos."
msgstr "הדפדפן שברשותך אינו תומך בהצגת סרטונים. עמך הסליחה!"

msgid "Facebook Statuses"
msgstr "סטאטוסים מפייסבוק"

**Comment by yotammanor** [comment]
Screenshots attached.

Things to note:

- The location of Facebook Statuses' Section in page.
- The difference between different attachment types - photos, videos, links
- The difference between a Youtube video and a Facebook uploaded video

image

image


image


image

**Comment by yotammanor** [comment]
@OriHoch You're up!

**Comment by OriHoch** [comment]
closing this PR, will open a new one with the translations

**Pull request closed without merging**
