### PR TITLE
Multiple issues

### PR DESCRIPTION
**Pull request by alonisser**
Running the tests throws lots of deprecation warnings. To allow future advance to django 1.8 removed the dependency on using  AUTH_PROFILE_MODULE (in oknesset code at least). Fixing the Deprecation warnings referenced in #475

### CODE REVIEW

**Comment by OriHoch** [comment]
@alonisser - thanks, great work!

could you please write in more detail about the changes in this pull request?

**Comment by OriHoch** [comment]
also - the tests are failing.. I recently fixed some unit tests, so if you update with hasadna master it might fix it..

**Comment by alonisser** [comment]
The test failures are somewhere in commits: ee611cb, a59d662 (I believe in this one.. ), I reverted them locally and everything passes, It also fails in Oknesset master before my merging my PR so nothing to do with this PR.. :(

**Comment by alonisser** [comment]
More details:
1. Adding abstain data to vote list and detail #514 (also schema migration and data migration  to support this)
2. Partial fixing #438 no ordering in committees agenda (part of the problem needs more attention, see my comment)

3. fix export bug #523 
4. Hiding sidebar in specific view as requested by @morchickit #520 
5. Remove deprecation warning (by fixing the deprecated thing.. ) to allow future upgrade
6. Some refactoring in method names, test classes (just starting here .. ) separation of concerns etc
7. General pep8 spacing issues

**Comment by OriHoch** [comment]
will continue in #529

**Pull request closed without merging**
