### PR TITLE
Splitting tag detail into knessets

### PR DESCRIPTION
**Pull request by otadmor**
These changes fix:
https://github.com/hasadna/Open-Knesset/issues/347
https://github.com/hasadna/Open-Knesset/issues/409

2 comments:
1) I didnt create many to many db relation between the different objects (laws, vote etc) to a knesset. I did the connection in the view.
2) I have added post_save action to tag new votes with old tags of law.

Ofir.

### CODE REVIEW

**Comment by OriHoch** [comment]
@otadmor - code looks good, thanks  :+1: 
I'll checkout the branch later to see what it looks like

**Comment by OriHoch** [comment]
Nice, I like the look of tag detail page, but there are some minor UX problems:
* it's not clear what the numbers mean (knesset number)
* when changing knesset number, the section titles don't change. So, for example, the title of "data form current knesset" remains as is - it's not clear what data I'm seeing there.. if I changes to previous knesset it's not current knesset anymore
* same goes for the sections of bills / votes / committee meetings - it's not clear if I'm looking at current data or data from previous knesset

Let me know if you can fix it soon otherwise maybe we will just merge as is

**Comment by otadmor** [comment]
How do you think it will be understandable? Im not that into UI.

**Comment by OriHoch** [comment]
@otadmor - 
image

**Comment by otadmor** [comment]
Thanks. Will be  done  today or the next.

**Comment by otadmor** [comment]
Done. Should I create a new pullrequest?

**Comment by OriHoch** [comment]
No

**Comment by OriHoch** [comment]
opened #420 to continue work on the UX/UI

**Pull request merged**
