### PR TITLE
close #350 + admin improvements + separation of tag page functionality from auxiliary to own app 

### LINKED ISSUE #350: minor improvements to committee meetings list on tag page
###  Reproduction Steps
* goto a tag page (like [this one](https://oknesset.org/tags/%D7%91%D7%98%D7%97%D7%95%D7%9F%20%D7%A4%D7%A0%D7%99%D7%9D/))
* look at the component that displays the committee meetings list

#### Expected
1. when hovering with the mouse cursor over a committee meeting everything gets an underline, including the ocmmittee name and the date, which looks kinda weird (on other lists, only the title gets an underline)
2. plenum meetings also appear and it's also a bit weird - title says "Committee meetings" but then you see a plenum meeting there.
3. if there are a lot of meetings - might need to limit the number of meetings we show there (that's what ofri ment with the more button)

uploads/db8256f8-c237-4ee6-8cff-458c48abbb89/blob

### PR DESCRIPTION
**Pull request by alonisser**

### CODE REVIEW

**Comment by OriHoch** [comment]
@alonisser -

There is an unrelated commit - c91090810e13cd90f8c6c4129e3fc14a7b1eaee0

I prefer it will be in a different pull request where we can discuss it.. specifically, I'm not sure we should have identifying information such as server ip, the key file name, directory paths in the repo

please don't open pull requests from master but open a branch for each feature, that way you can have control over what goes into the pull request

**Comment by alonisser** [comment]
@OriHoch : Ok, so remove this from the current branch?

**Comment by OriHoch** [comment]
@alonisser 
it's best to have a separate branch for each feature

so, in this case, I would do something like this:

* close this pull request
* checkout the last relevant commit
  * $ git checkout ea691d8dfc5f19253c082f0ea65eee43fd5cd0a2
* create a new branch for this issue
  * $ git checkout -b 350-minor-improvements-to-committee-meetings-list-on-tag-page
* push and then create a new pull request from that branch

then, create a new branch from your master for the ansible work

generally, it's best not to work on the master branch

**Comment by alonisser** [comment]
No problems I'll separate the PR's (no need for git instructions.. :) )
Actually I differ on not working on master branch. in the CI/CD world it's quite common.. especially when using PR's for gate keeping, but in this case I agree separating would be easier. 
Will do today

**Pull request closed without merging**
